var b,g,k,m,u;k=g=b=null;m={h:0};u="_GreenFlag _YellowFlag _RedFlag _CheckeredFlag _YellowSector _SlowZone _Stop".split(" ");w();function x(c){var d=y;var a=new XMLHttpRequest;a.onreadystatechange=function(){4==a.readyState&&d(a,c)};a.open("GET",c.o+"?t="+Date.now(),!0);a.send()}
function y(c,d){null!=k&&clearInterval(k);if(200==c.status)try{b=JSON.parse(c.responseText),g=d}catch(p){}if(null!=b){z();var a;var e=document.createDocumentFragment();if(""!=b.ImageHaut.Url){var f=A("div",e,null,null,{"class":"logo-haut"});""!=b.ImageHaut.Lien&&(f=A("a",f,null,null,{href:b.ImageHaut.Lien,target:"_blank"}));A("img",f,null,null,{src:b.ImageHaut.Url})}f=A("div",e,"titre-course");""!==b.Drapeau&&A("img",f,null,null,{src:"Images/"+u[b.Drapeau]+".png"});if(0==b.Page.length)A("h1",f,null,
b.Titre);else{var l=A("select",f,"page");for(a=0;a<b.Page.length;a++){var h=document.createElement("option");h.value=a+1;h.text=b.Page[a];h.value==g.i&&(h.selected=!0);l.appendChild(h)}g.i=l.value;l.onchange=w}if(0!=b.Filtre.length){l=A("select",f,"filtre");for(a=0;a<b.Filtre.length;a++)h=document.createElement("option"),h.value=0==a?"":0==b.TypeDonnees?b.Filtre[a]:a-1,h.text=b.Filtre[a],h.value==g.g&&(h.selected=!0),l.appendChild(h);g.g=l.value;l.onchange=B}""!==b.Drapeau&&A("img",f,null,null,{src:"Images/"+
u[b.Drapeau]+".png"});""!==b.TextePerso&&A("p",f,null,b.TextePerso,{"class":"texte-perso"});f=A("div",e,"info-course");A("div",f,"heure-jour","<span>"+m.j+"</span>");A("div",f,"temps-course","<span>"+m.l+"</span> <span>"+m.m+"</span>");f=A("div",e,"classement");C(f);0!=b.Messages.length&&(f=A("div",e,"message"),A("p",f,null,b.Messages));""!=b.ImageBas.Url&&(f=A("div",e,null,null,{"class":"logo-bas"}),""!=b.ImageBas.Lien&&(f=A("a",f,null,null,{href:b.ImageBas.Lien,target:"_blank"})),A("img",f,null,
null,{src:b.ImageBas.Url}));h=A("a",e,"chronelec","Logiciel Elite v3 - www.chronelec.com",{href:"https://www.chronelec.com",target:"_blank"});A("img",e,"image-zoom",null,{src:""});f=document.getElementById("resultat");if(null!=f){for(;f.firstChild;)f.firstChild.remove();f.appendChild(e);e=D(h);e=e.substring(5,e.length-1).replace(/ /g,"").split(",");h.style.cssText="display: block !important; visibility: visible !important; color: "+(186<.299*e[0]+.587*e[1]+.114*e[2]?"#000000C0":"#FFFFFFC0")+"!important;"}}k=
setInterval(E,1E3)}function E(){m.h+=1E3;if(null==b||m.h>=b.Rafraichir)m.h=0,w();else{z();var c=document.getElementById("heure-jour");null!=c&&1<=c.children.length&&(c.children[0].innerHTML=m.j);c=document.getElementById("temps-course");null!=c&&2<=c.children.length&&(c.children[0].innerHTML=m.l,c.children[1].innerHTML=m.m)}}
function z(){if(6!=b.Drapeau){var c=1E3*Math.round(Date.now()/1E3);var d=c-(new Date(b.HeureJourUTC)).getTime();if(0>d||1==b.FigerTemps)d=0}else c=(new Date(b.HeureJourUTC)).getTime(),d=0;m.j=F(c+6E4*b.FuseauHoraire,!0);m.l=-1!=b.TempsEcoule?F(b.TempsEcoule+d,!1):"";m.m=-1!=b.TempsRestant?"-"+F(Math.max(b.TempsRestant-d,0),!1):""}function w(){var c={};var d=document.getElementById("page");c.i=null!=d?d.value:1;d=document.getElementById("filtre");c.g=null!=d?d.value:"";c.o="r"+c.i+".json";x(c)}
function B(){var c=document.getElementById("filtre");g.g=c.value;var d=document.createDocumentFragment();C(d);c=document.getElementById("classement");null!=c&&(c.firstChild&&c.firstChild.remove(),c.appendChild(d))}
function A(c,d,a,e,f){a=void 0===a?null:a;e=void 0===e?null:e;f=void 0===f?null:f;var l;c=document.createElement(c);null!=a&&(c.id=a);null!=e&&("[object Array]"===Object.prototype.toString.call(e)?c.innerHTML=e.join("<br>"):c.innerHTML=e);if(null!=f)for(l in f)c.setAttribute(l,f[l]);null!=d&&d.appendChild(c);return c}
function C(c){var d;var a=A("div",c);if(0==b.TypeDonnees)G(a,b.Donnees);else for(d=0;d<b.Donnees.length;d++)if(""==g.g||d==g.g)A("span",a,null,b.Donnees[d].Nom,{"class":"titre"}),G(a,b.Donnees[d].CH);c.appendChild(a)}
function G(c,d){var a,e;var f=-1;var l=""==g.g?1:2;var h=document.createElement("table");var p=h.createTHead();h.appendChild(p);var v=p.insertRow(-1);p.appendChild(v);var n=1;for(a=0;a<b.Colonnes.length;a++){if(0==b.Colonnes[a].ModeAffichage||b.Colonnes[a].ModeAffichage==l){var q=A("th",v,b.Colonnes[a].Nom,b.Colonnes[a].Texte);h.classList.add("c"+n+"-"+b.Colonnes[a].Alignement);n++}"Categorie"==b.Colonnes[a].Nom&&(f=a)}p=document.createElement("tbody");h.appendChild(p);for(a=0;a<d.length;a++)if(""==
g.g||-1==f||d[a][f]==g.g)for(v=p.insertRow(-1),e=0;e<b.Colonnes.length;e++)if(0==b.Colonnes[e].ModeAffichage||b.Colonnes[e].ModeAffichage==l)q=v.insertCell(-1),1==b.Colonnes[e].ModeImage&&""!=d[a][e]?(n=A("img",q,null,null,{src:"Images/"+d[a][e]+".png"}),n.onmouseover=function(H){return function(r){var I=H.src;var t=document.getElementById("image-zoom");null!=t&&(t.src=I,t.style.left=r.pageX-r.offsetX+r.target.offsetLeft+"px",t.style.top=r.pageY-r.offsetY-2*r.target.offsetTop+"px",t.style.visibility=
"visible")}}(n),n.onmouseout=J):"{"==d[a][e].charAt(0)?(n=d[a][e].indexOf("}"),-1!=n?(q.innerHTML=d[a][e].substring(n+1),q.setAttribute("class",d[a][e].substring(1,n))):q.innerHTML=d[a][e]):q.innerHTML=d[a][e];c.appendChild(h)}function J(){var c=document.getElementById("image-zoom");null!=c&&(c.style.visibility="hidden")}
function F(c,d){var a=new Date(c);var e="";!0===d&&(e+=("0"+a.getUTCDate()).slice(-2)+"/"+("0"+(a.getUTCMonth()+1)).slice(-2)+"/"+a.getUTCFullYear());!0===d&&(e+=" ");return e+=("0"+a.getUTCHours()).slice(-2)+":"+("0"+a.getUTCMinutes()).slice(-2)+":"+("0"+a.getUTCSeconds()).slice(-2)}function D(c){var d=window.getComputedStyle(c).getPropertyValue("background-color");"rgba(0, 0, 0, 0)"==d&&null!=c.parentNode&&(d=D(c.parentNode));return d};